### ISSUE TITLE
IE - TypeError: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by Pumych** [Mobiletainment/ng-clamp#1]
Thought that I found a working solution but got this error in IE.

**Comment by Mobiletainment** [comment]
Thanks for pointing this out and sorry for the late reply.
I'm going to fix this today.

**Comment by Mobiletainment** [comment]
the issue is fixed and I've also incorporated multi-line truncation for Internet Explorer. I hope its not too late for you. BR
